version: '3.8'
services:
  db:
    image: postgres:latest
    restart: always
    environment: 
      - POSTGRES_PASSWORD=password
    ports:
      - "5432:5432"
    volumes: 
      - "dbdata:/var/lib/postgresql/data"
      
  web:
    build: .
    ports: 
      - "3000:3000"
    depends_on: 
      - db
    environment: 
      - DATABASE_URL=postgres://postgres:password@db:5432/postgres
    volumes: 
      - .:/app

  elasticsearch:
    image: docker.elastic.co/elasticsearch/elasticsearch:7.14.0
    environment:
      - discovery.type=single-node
    ports:
      - 9200:9200
      - 9300:9300

volumes: 
  dbdata:
